# Generated by Django 5.0.3 on 2024-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('register_number', models.IntegerField()),
                ('register_course', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('WOMEN', 'women'), ('MEN', 'men'), ('OTHER', 'other'), ('GIRL', 'girl'), ('BOY', 'boy')], default=True, max_length=10)),
                ('exam_start', models.DateField()),
                ('exam_end', models.DateField()),
                ('comments', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
